import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const roboto = Roboto({
  subsets: ["vietnamese"],
  weight: ["100", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={roboto.className}>
        <Button variant={"default"}>
          <Link href={"/"}>Home Page</Link>
        </Button>
        <div>{children}</div>
      </body>
    </html>
  );
}
